# Site settings
title: cjrams
description: 'A mobile developer'
url: 'https://cjrams.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Carlos Jimenez Rams'
  email: cjrams@gmai.com
  github_username:  cjrams
  linkedin_username:  cjrams
#  twitter_username: cjrams
#  facebook_username: cjrams

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
